import "./globals.css";
import type { Metadata } from "next";
import { Syne } from "next/font/google";

const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cold Stash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={syne.className}>{children}</body>
    </html>
  );
}
